name: TestEnv

on:
  workflow_dispatch:

env:
  env_var: ${{ vars.ENV_CONTEXT_VAR }}

jobs:
  default:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: echo VAR
        run: echo ${{ vars.VAR }}
        
  stagging:
    runs-on: ubuntu-latest
    continue-on-error: true
    environment: stagging    
    steps:
      - name: echo VAR
        run: echo ${{ vars.VAR }}

  prod:
    continue-on-error: true
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: echo VAR
        run: echo ${{ vars.VAR }}
