name: TestEnv

on:
  workflow_dispatch:

env:
  env_var: ${{ vars.ENV_CONTEXT_VAR }}

jobs:
  dev:
    runs-on: ubuntu-latest
    continue-on-error: true
    environment: Prod
    
    steps:
      - name: echo A_VAR
        run: echo ${{ vars.A_VAR }}

  prod:
    continue-on-error: true
    runs-on: ubuntu-latest
    environment: Prod

    steps:
      - name: echo A_VAR
        run: echo ${{ vars.A_VAR }}
