name: TestEnv

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Retrieve the secret and decode it to a file
        env:
          KEY: ${{ secrets.API_KEY }}
        run: echo $KEY | base64
